# Configure this Discovery Server
eureka:
  instance:
    hostname: ICS-LT-CPBR693
  client: 
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 1111